@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "core.controller.Controller",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_104069929 { 
   	label=model
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Entity937501722[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Entity</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

EntityManager937501722[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)EntityManager</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ persist(e: Entity)</TD></TR>
<TR><TD ALIGN="LEFT" >+ persist(e: Entity, field: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ persist(e: Entity, id: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ persist(e: Entity, id: int, field: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ remove(e: Entity, id: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ remove(e: Entity, id: int, field: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

QueryBuilder937501722[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)QueryBuilder</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   alias: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   condition: StringBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   entity: Entity [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   groupBy: StringBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   having: StringBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   insertData: StringBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   insertion: StringBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   integerParameters: HashMap&lt;Integer, Integer&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   joins: StringBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   naturalCase: Boolean [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   orderBy: StringBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   projection: StringBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   query: StringBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   statement: PreparedStatement [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   stringParameters: HashMap&lt;Integer, String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   table: StringBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   ucFirst: Boolean [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   values: StringBuilder [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addValues(primaryKey: String): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ andHaving(condition: String): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ andWhere(condition: String): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >- generateSnakeTailString(value: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >- getInsertColumns(primaryKey: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >- getInsertData(primaryKey: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getPersistResult()</TD></TR>
<TR><TD ALIGN="LEFT" >+ groupBy(field: String): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ innerJoin(table: String, key: String): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ innerJoin(table: String, left: String, right: String): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertInto(): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertOrm(): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertOrm(primaryKey: String): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ orHaving(condition: String): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ orWhere(condition: String): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ orderBy(orderBy: HashMap&lt;String, String&gt;): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ select(fields: String): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ selectOrm(): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ setParameter(parameter: Integer, value: int): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ setParameter(parameter: Integer, value: String): QueryBuilder</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Repository937501722[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Repository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   alias: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   entity: Entity [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   naturalCase: Boolean [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   queryBuilder: QueryBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   ucFirst: Boolean [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># createQueryBuilder(): QueryBuilder</TD></TR>
<TR><TD ALIGN="LEFT" ># doFind(id: int, field: String): Entity</TD></TR>
<TR><TD ALIGN="LEFT" >+ find(id: int): Entity</TD></TR>
<TR><TD ALIGN="LEFT" >+ find(id: int, field: String): Entity</TD></TR>
<TR><TD ALIGN="LEFT" >+ findAll(): ArrayList&lt;? extends Entity&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findAll(orderBy: HashMap&lt;String, String&gt;): ArrayList&lt;? extends Entity&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findBy(condition: HashMap&lt;String, String&gt;): ArrayList&lt;Entity&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findOneBy(condition: HashMap&lt;String, String&gt;): Entity</TD></TR>
<TR><TD ALIGN="LEFT" >+ setAlias(alias: String): Repository</TD></TR>
<TR><TD ALIGN="LEFT" >+ setEntity(entity: Entity): Repository</TD></TR>
<TR><TD ALIGN="LEFT" >+ setUcFirst(): Repository</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1243020381 { 
   	label=global
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Resources1176438574[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Resources</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getConfig(file: String): URL</TD></TR>
<TR><TD ALIGN="LEFT" >+ getImage(image: String): URL</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Response1176438574[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Response</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ redirectToController(listener: ActionListener)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Session1176438574[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Session</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- bytesToHex(bytes: byte[]): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ copy(key: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ destroyBenutzer()</TD></TR>
<TR><TD ALIGN="LEFT" >+ destroySession()</TD></TR>
<TR><TD ALIGN="LEFT" >- digest(input: byte[]): byte[]</TD></TR>
<TR><TD ALIGN="LEFT" >+ get(key: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getHash(string: String): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1298275357 { 
   	label=entity
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Kollegiat1298275357[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Kollegiat</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   betreuerId: Integer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   kid: Integer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   tutorId: Integer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   vorname: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ setBetreuerID(betreuerID: Integer): Kollegiat</TD></TR>
<TR><TD ALIGN="LEFT" >+ setName(name: String): Kollegiat</TD></TR>
<TR><TD ALIGN="LEFT" >+ setTutorID(tutorID: Integer): Kollegiat</TD></TR>
<TR><TD ALIGN="LEFT" >+ setVorname(vorname: String): Kollegiat</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1950800714 { 
   	label=repository
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   AntragRepository1950800714[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AntragRepository</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

BenutzerRepository1950800714[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BenutzerRepository</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FachRepository1950800714[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FachRepository</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

KollegiatRepository1950800714[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)KollegiatRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getKollegiatJoinAntrag(kid: int): ArrayList&lt;HashMap&lt;String, String&gt;&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

LehrkraftRepository1950800714[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)LehrkraftRepository</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ThemaRepository1950800714[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ThemaRepository</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_308865814 { 
   	label=kollegiat
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   DetailPanel653864717[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DetailPanel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   fieldBetreuer: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fieldNachname: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fieldTutor: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fieldVorname: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   gbc: BagConstraints [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   gridBagLayout: GridBagLayout [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   kollegiat: Kollegiat [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># init()</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateFields()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_3619493 { 
   	label=view
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   BagConstraints1632063596[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BagConstraints</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

View1632063596[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)View</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   cardLayout: CardLayout [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   frame: JFrame [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   imagePath: URL [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># init()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_637428636 { 
   	label=controller
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   AntragController637428636[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AntragController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ index(e: ActionEvent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AppController637428636[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AppController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ index(e: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ restartApplication(e: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ show(e: ActionEvent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AuthenticationController637428636[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AuthenticationController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ index(e: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ login(e: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ logoff(e: ActionEvent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Controller712365749[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Controller</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   repository: Repository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   view: View [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ actionPerformed(e: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addLayoutComponent(c: Component, constraint: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ redirectToController(listener: ActionListener)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FachController637428636[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FachController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ index(e: ActionEvent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

KollegiatController637428636[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)KollegiatController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ index(e: ActionEvent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

LehrkraftController637428636[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)LehrkraftController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ index(e: ActionEvent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ThemaController637428636[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ThemaController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ index(e: ActionEvent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_96801 { 
   	label=app
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   AppMenuBar1194705752[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AppMenuBar</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getComponent(view: View): JMenuBar</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
AppController637428636 -> AppMenuBar1194705752[label="index() -> getComponent()"];
AppController637428636 -> DetailPanel653864717[label="show() -> updateFields()"];
AppController637428636 -> Kollegiat1298275357[label="show() -> setName()"];
AppController637428636 -> KollegiatRepository1950800714[label="index() -> getKollegiatJoinAntrag()"];
AppController637428636 -> Resources1176438574[label="show() -> getImage()"];
AuthenticationController637428636 -> Repository937501722[label="login() -> findOneBy()"];
Controller712365749 -> AntragController637428636[arrowhead=none, arrowtail=empty, dir=both];
Controller712365749 -> AppController637428636[arrowhead=none, arrowtail=empty, dir=both];
Controller712365749 -> AuthenticationController637428636[arrowhead=none, arrowtail=empty, dir=both];
Controller712365749 -> FachController637428636[arrowhead=none, arrowtail=empty, dir=both];
Controller712365749 -> KollegiatController637428636[arrowhead=none, arrowtail=empty, dir=both];
Controller712365749 -> LehrkraftController637428636[arrowhead=none, arrowtail=empty, dir=both];
Controller712365749 -> Repository937501722[label="repository
[0..1]"];
Controller712365749 -> Response1176438574[label="redirectToController() -> redirectToController()"];
Controller712365749 -> ThemaController637428636[arrowhead=none, arrowtail=empty, dir=both];
Controller712365749 -> View1632063596[label="view
[0..1]"];
DetailPanel653864717 -> BagConstraints1632063596[label="gbc
[0..1]"];
DetailPanel653864717 -> Kollegiat1298275357[label="kollegiat
[0..1]"];
Entity937501722 -> Kollegiat1298275357[arrowhead=none, arrowtail=empty, dir=both];
QueryBuilder937501722 -> Entity937501722[label="entity
[0..1]"];
Repository937501722 -> AntragRepository1950800714[arrowhead=none, arrowtail=empty, dir=both];
Repository937501722 -> BenutzerRepository1950800714[arrowhead=none, arrowtail=empty, dir=both];
Repository937501722 -> Entity937501722[label="entity
[0..1]"];
Repository937501722 -> EntityManager937501722[arrowhead=none, arrowtail=empty, dir=both];
Repository937501722 -> FachRepository1950800714[arrowhead=none, arrowtail=empty, dir=both];
Repository937501722 -> KollegiatRepository1950800714[arrowhead=none, arrowtail=empty, dir=both];
Repository937501722 -> LehrkraftRepository1950800714[arrowhead=none, arrowtail=empty, dir=both];
Repository937501722 -> QueryBuilder937501722[label="queryBuilder
[0..1]"];
Repository937501722 -> ThemaRepository1950800714[arrowhead=none, arrowtail=empty, dir=both];
View1632063596 -> Resources1176438574[label="init() -> getImage()"];
View1632063596 -> Response1176438574[label="init() -> redirectToController()"];
    
}
@enduml